<?php

namespace ContainerOSQ5YLk;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProductUpdateListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\ProductUpdateListener' shared autowired service.
     *
     * @return \App\EventListener\ProductUpdateListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/ProductUpdateListener.php';

        return $container->privates['App\\EventListener\\ProductUpdateListener'] = new \App\EventListener\ProductUpdateListener($container->getEnv('SHOPIFY_API_URL'), $container->getEnv('SHOPIFY_ACCESS_TOKEN'), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
