doctrine:
    dbal: { connections: { default: { host: db, port: '3306', user: pimcore, password: pimcore, dbname: pimcore, mapping_types: { enum: string, bit: boolean }, server_version: '10.11.5-MariaDB-1:10.11.5+maria~ubu2204' } } }
