<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTh9qErC\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTh9qErC/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerTh9qErC.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerTh9qErC\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerTh9qErC\App_KernelDevDebugContainer([
    'container.build_hash' => 'Th9qErC',
    'container.build_id' => '858b39b0',
    'container.build_time' => 1694272210,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTh9qErC');
